### ISSUE TITLE
Discuss javascript built tool enhancements

### ISSUE THREAD

**Issue by tburry** [vanilla/vanilla-cli#43]
I'd like to discuss the build tool's javascript functionality. Here is some of the functionality I want:

## Addon concatenation

Addons have their javascript built seperately and will be included in sequence for development and concatenated in production (eventually).

- We can have a core javascript libary that all addons can assume exists. Addons should not include the core javascript in each build.
- Can we still get hot reloading with multiple javascript files in development? Is there another way we can handle development? (ex. devs just specify the addons to include in development builds in a JSON somewhere).

## React.js capability

We want react.js functionality in core. I think this just means adding it the the config and making sure it is built into the core bundle.

## Regular js

We have a lot of plain non-react javascript that will have to be built or ported. It would be nice to be able to program in ES6 modules though.

## Conditionally loading polyfills

Can we have conditionally loaded polyfills asyncronously loaded into older browsers? It would be nice to not have to think about this loading.

So for example, I specify **babel-polyfill** in a polyfills config somewhere and it gets built into a seperate javascript file and automatically loaded if necessary in older browsers.

## Dynamically loading libraries

This is similar to conditional polyfill loaders, but would allow us to specify some larger, rarely used libraries to load dynamically.

- A couple examples would be c3.js and swagger-ui.js. Both these libraries are only required on one page in the dashboard and it would be nice to load them on-demand.
- The best solution would involve allowing developers to specify dependencies using ES6 like usual and then specifying some of those dependencies as dynamic in a config somewhere and then having webpack know to load them asyncronously. If webpack has a plugin that can do this we could make an endpoint to resolve the libraries in a normalized way.
- If the above is not possible the programmer could ask to dynamically load the library.

## Multiple entry points

Addons will often have several javascript files. Here are some examples:

- Addons will often have user-faceing javascript administrative facing javascript. These are almost like two seperate applications.
- Addons may need to include other vendor libraries that are dynamically loaded.
- In the future we may have a mobile javascript app which will need a seperate entry point.

## Best practicies for jQuery and globals like window and document

Let's go over best practices for converting some of our current code into ES6.

- Currently we use IEFE's to protect the global scope. I think we can convert these to ES6 modules.
- In old javascript it's a best practice to take browser globals as parameters in your IEFE so that they can be changed later if necessary. Is there an ES6 module equivalent?

**Comment by Charrondev** [comment]
- React. This is easy enough. I just need to add an additional babel preset into the mix. I'm currently using `babel-preset-env` with supported browsers as the target, but I would just need to add `babel-preset-react` as well. We might want to also consider adding [babel-plugin-transform-object-rest-spread](https://babeljs.io/docs/plugins/transform-object-rest-spread/) as that is still at stage 3 and isn't part of the `env` preset.

It's the difference between

```js
const obj1 = {
    key1: "foo",
    key2: "bar",
};

const obj2 = {
    key3: "foobar",
};

// This

const obj3 = {
    ...obj1,
    ...obj2,
    someOtherKey: 'foobarfoo',
};

// vs this

const obj3 = Object.assign({},
    obj1,
    obj2, {
    someOtherKey: 'foobarfoo',
});
```

It's not a huge difference, but worth considering.

**Comment by DaazKu** [comment]
The first one is way better. It is shorter and easier to read.

**Comment by Charrondev** [comment]
## Addon concatenation
This is easily the most difficult thing here. I think we need to define first what the requirements are. The biggest issue I can think of with this is duplicating code.

There are few different ways to import code.

### ES6 static imports
```js
import * as React from 'react';
import VanillaPopup from '@CoreComponents';

export default class SomeComponent extends React.Component {
    render() {
        return <VanillaPopup someProp="foo"/>
    }
}
```

### Stage 3 TC39 dynamic import proposal (Webpack implements this)
```js
export default function makeSomeComponent() {
    const React = await import('react');
    const VanillaPopupComponent = await import('../VanillaPopupComponent');

    class SomeComponent extends React.Component {
        render() {
            return <VanillaPopup someProp="foo"/>
        }
    }

    return SomeComponent;
}
```

I would prefer that our modules look like the former. It seems like we could make that happen with [Webpack Externals](https://webpack.js.org/configuration/externals/). Basically anything we want to share we would attach as a global variable variable as well as a module, and then when building addons that aren't part of core Vanilla we can tell webpack essentially "We promise these will be in the page this module is loaded so don't actually put it in this bundle".

We could also do a similar thing for our most common large libraries like React, and Redux, moment.js if we use it, etc.

**Comment by tburry** [comment]
FYI: I updated the description of this issue with more in-depth requirements.

**Comment by Charrondev** [comment]
Looking at this it seems like we are going to have a couple of different build process that are used to make this all come together

## vanilla build --process="core"
Build the core vanilla javascript.

### DLL Files
Core vanilla code can be split into into separate bundles with the [Webpack DLL plugin](https://webpack.js.org/plugins/dll-plugin/). The DLL plugin generates a bundle as well as a json file to map these dependancies in a later build step. The addon bundling process will be able to use the mapping files to build against the core javascript without actually needing to touch it. This will also greatly increase build times.

Almost every single external external dependency should be in the main DLL. 

Libraries that are both large, but not commonly could be imported in the following way:
1. Add the dependency to node_modules
1. Use a webpack dynamic import. Make sure to catch any errors thrown by the Promise (for example if the bundle isn't loaded.) This way the rest of the pages javascript can still run independently.
1. This dynamic import will generate an additional bundle. The controller will need to include this bundle only on the necessary pages.

### Core bundles

There will be 2 types of core bundles.

- **dashboard.vendor.dll.js** - Contains dashboard's most common dependencies.
- **dashboard.dll.js** - Contains the actual js for the dashboard.
- **vanilla.vendor.dll.js** -  Contains the frontend's most common dependencies.
- **vanilla.bundle.js** - Contains the actual frontend code.

Code may be duplicated between the dashboard and the vanilla bundles. I don't really see the benefit of trying to break out common chunks, even for vendor files since most people don't visit the dashboard anyways. Maybe it would be something to look at in the future, but for right now I don't see it as bringing any significant performance improvements worth complicating the build even further.

## vanilla build --process="addon"
Addons will be able to output 2 bundles. A dashboard bundle and frontend (vanilla) bundle. The `*` in the bundle name will be replaced with the addon key.

#### *.dashboard.bundle.js

Bundle targeting enhancements to the dashboard. This will build against `dashboard.vendor.dll.js` and `dashboard.dll.js`.

####*.bundle.js
Bundle targeting enhancements to the dashboard. This will build against `vanilla.vendor.dll.js` and `vanilla.dll.js`.

## Extra Parameters
- `--rebuild-vendors` - Rebuild the vendor files as well. The vendor files will not be built by default to speed up builds. They can be rebuilt when necessary.
